### PR TITLE
fix:305 only serialize protofields

### LINKED ISSUE #305: gogo jsonpb tries to serialize non proto field
We have a proto generated struct which also contains a non proto field for caching purposes, like so

```go
type PID struct {
	Address string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`

	p *Process //<-- this field
}
```

This works nice when serializing as a normal proto message.
But, when suing jsonpb, there is an error thrown that there is no encoder for `Process`.
Why is gogo jsonpb trying to serialize a field that is not part of the proto contract, has no proto tags and clearly is not a proto type?

### PR DESCRIPTION
**Pull request by rogeralsing**
This fixes #305
I am however not sure if this is the correct way to go about it, or if it even acceptable in terms of backwards compat to introduce this.

My understanding is however that when serializing using jsonpb, you only want to deal with fields defined in your proto contracts

### CODE REVIEW

**Comment by awalterschulze** [comment]
I don't think this break backwards compatibility.
Everything without a protobuf tag was breaking anyway.
I would like a test though.

**Comment by rogeralsing** [comment]
I'm on it

File: jsonpb/jsonpb_test.go [hunk 1]
```diff
@@ -684,3 +684,33 @@ func (m *dynamicMessage) UnmarshalJSONPB(jum *Unmarshaler, json []byte) error {
 	m.rawJson = string(json)
 	return nil
 }
+
+// customFieldMessage implements protobuf.Message but is not a normal generated message type.
+type customFieldMessage struct {
```
Comment (rogeralsing) [inline jsonpb/jsonpb_test.go]: This is similar to the dynamicMessage but w/o the MarshalJSONPB code.
The message has no other fields than the custom field that should be ignored.
The accompanying test ensures that the  JSON output is `{}` of this type

**Comment by rogeralsing** [comment]
Done.
There however seems to be a failing test now due to the change.
```
--- FAIL: TestMarshaling (0.00s)
        jsonpb_test.go:437: oneof, set: got [{}] want [{"title":"Grand Poobah"}]
```

It's not clear to me why this fails with this change. 
I will dig deeper

**Comment by awalterschulze** [comment]
Good luck.

File: jsonpb/jsonpb_test.go [hunk 2]
```diff
@@ -426,6 +426,7 @@ var marshalingTests = []struct {
 	{"BoolValue", marshaler, &pb.KnownTypes{Bool: &types.BoolValue{Value: true}}, `{"bool":true}`},
 	{"StringValue", marshaler, &pb.KnownTypes{Str: &types.StringValue{Value: "plush"}}, `{"str":"plush"}`},
 	{"BytesValue", marshaler, &pb.KnownTypes{Bytes: &types.BytesValue{Value: []byte("wow")}}, `{"bytes":"d293"}`},
+	{"ignore non proto field", marshaler, &customFieldMessage{someField: "Ignore me"}, `{}`},
```
Comment (rogeralsing) [inline jsonpb/jsonpb_test.go]: Custom field message added to marshal test data

**Comment by rogeralsing** [comment]
OK, there seems to be code in the repo that relies on non mapped fields are getting serialized:
https://github.com/Serabe/protobuf/blob/a93a2631941938aa74d8c61e3603bca41ff93ee9/test/issue260/models.go#L15

My reasoning around jsonpb is that just as Protobuf binary format is cross platform, so is Proto JSON.
It's meant to mean the same even if you pass a Go message to a C# system etc.

Thoughts here?
Is this a no go?
Could an option be added to the marshaller to opt in for this?
cc @awalterschulze

**Comment by awalterschulze** [comment]
I think its ok to go and add a protobuf tag for those two fields.
@Serabe what do you think?

**Comment by rogeralsing** [comment]
All tests pass. 
I added my test data in the jsonpb_test.go, do you want this isolated as a separate folder under /tests instead?

**Comment by awalterschulze** [comment]
I think I would just prefer the test in a different file, if you don't mind.
Some explicit like jsonpb_gogo_test.go
It just makes merging in future changes from golang/protobuf easier for me.

But the rest of the change looks perfect :)

**Comment by awalterschulze** [comment]
You can also add yourself to the CONTRIBUTORS or AUTHORS as appropriate.

**Comment by awalterschulze** [comment]
Good work :)
Thank you very much :)

**Comment by Serabe** [comment]
Anything that requires reflection at some point requires struct tags. It is a known limitation on `typedecl`, but it can be manually added if needs be.

That said, if we add struct tags to all models, then we stop testing that `typedecl` works.

**Comment by awalterschulze** [comment]
Hmmm thats a good point.

We should probably remove the tags again, but to get the jsonpb test to pass, maybe we should implement the JSONPBUnmarshaler interface for these structs?

That way we get best of both?

**Comment by Serabe** [comment]
What would be needed to implement those?

**Comment by awalterschulze** [comment]
I think this fixes the situation.
https://github.com/gogo/protobuf/commit/dda3e8acadcc9affc16faf33fbb229db78399245
What do you think?

**Comment by Serabe** [comment]
👍

**Comment by awalterschulze** [comment]
Ok great.
Thanks again for reviewing :)
